core/urls.py
from django.urls import path
from core.views import index, send
app_name = 'core'
urlpatterns  = [
    path('', index, name='index'),
    path('send', send, name='send')
]

mailer/urls.py
from django.urls import path, include
import core

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',include('core.urls'))

]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms


class EmailListForm(forms.Form):
    email_list = forms.CharField(label="Enter emails i.e. email_1@abc.com, email_2@abc.com")
    html_file = forms.FileField(label="HTML file")

core/views.py
from django.shortcuts import render,reverse, render_to_response, redirect
from django.http import HttpResponseRedirect

from smtplib import SMTP
from email.mime.text import MIMEText

from .forms import EmailListForm
from mailer import settings

from os import path
from datetime import datetime


def content_setter(sending_to, file_name):
    email_temaplate = open(file_name, 'r+')
    message = email_temaplate.read()
    my_email = MIMEText(message, "html")
    my_email["Subject"] = "Hello!"

    send_to = sending_to

    email_server = SMTP(settings.EMAIL_SMTP_SERVER, settings.EMAIL_SERVER_PORT)
    email_server.starttls()
    email_server.login(settings.SENDER_EMAIL, settings.SENDER_EMAIL_PASSWORD)
    email_server.sendmail(settings.SENDER_EMAIL, send_to, my_email.as_string())

    return my_email


def handle_uploaded_file(f):

    file_name = path.join(settings.MEDIA_ROOT, f'{int(datetime.now().timestamp())}.html')
    #file will be uploaded to media directory
    with open(file_name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    
    return file_name


def send(request):
    try :
        file = request.FILES['html_file']
        file_name = handle_uploaded_file(file)
        email_list = request.POST['email_list'].split(',')
        final_email = {}

        for email in email_list:
            try:
                content_setter(email, file_name)
                final_email[email] = "Sent"
            except Exception as e:
                if settings.DEBUG:
                    final_email[email] = f"Error: {e}"
                else:
                    final_email[email] = f"Error: Something went wrong while sending email"
        return render_to_response("core/layout.html", {"final_email": final_email, "form": EmailListForm()})
    except KeyError:
        return HttpResponseRedirect(reverse('core:index'))


def index(request):
    return render(request, 'core/layout.html', {"form": EmailListForm()})

core/templates/core/email_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <center>
        <h1>Hello</h1>
        This is HTML 5 <br/>
        HELLO EMAIL TEMPLATE
    </center>
</body>
</html>

core/templates/core/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django People</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Django : Email Sender</h1>
          <hr class="mt-0 mb-4">
            <h4>Enter E-Mail List you want to send email for</h4>
            {% load crispy_forms_tags %}
            <form action="{% url 'core:send' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Send</button>
            </form>
            {% if final_email %}
                <br>
                <br>
                <h5>Report</h5>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">E-mail</th>
                            <th scope="col">Result</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for email,result in final_email.items %}
                        <tr>
                            <td>{{email}}</td>
                            <td>{{ result }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            {% endif %}
        </div>
      </div>
    </div>
</body>
</html>